### ISSUE TITLE
DR-HPF002S : Incorrect vertical angle limit

### ISSUE THREAD

**Issue by Zerreth** [JeffSteinbok/hass-dreo#150] opened 2024-08-07 22:40 UTC
DR-HPF002S Vertical angle actually supports -30 to +90 degrees. Currently it only goes from 0 to +90 degrees.

**Comment by JeffSteinbok** [comment] 2024-08-26 19:45
Duplicate of #106

**Closed by JeffSteinbok** 2024-08-26 19:45 UTC
