### ISSUE TITLE
Fans aren't working. Getting this for on and off

### ISSUE THREAD

**Issue by MacDaddy5157** [JeffSteinbok/hass-dreo#151] opened 2024-08-10 12:45 UTC
Entity None (<class 'custom_components.dreo.fan.DreoFanHA'>) does not set FanEntityFeature.TURN_OFF but implements the turn_off method.

**Comment by JeffSteinbok** [comment] 2024-08-10 16:49
What version of the integration are you using?

**Comment by JeffSteinbok** [comment] 2024-08-26 19:40
Duplicate of #154

**Closed by JeffSteinbok** 2024-08-26 19:40 UTC
