### ISSUE TITLE
Request to add DR-HCF001

### ISSUE THREAD

**Issue by 67jeffh** [JeffSteinbok/hass-dreo#103] opened 2024-05-23 00:50 UTC
Model - DR-HCF001
Number of speeds the fan supports 12
Does the fan support oscillating - no
What preset modes are supported 
Fan: normal,  sleep, natural,  auto
Light: Dimmer, color temperature 2700 - 6700
Is temperature supported? No

**Comment by JeffSteinbok** [comment] 2024-05-26 19:57
Duplicate of #86

**Closed by JeffSteinbok** 2024-05-26 19:57 UTC
Labels: duplicate
