### ISSUE TITLE
Add support for model(s): MC710S

### ISSUE THREAD

**Issue by gszuch** [JeffSteinbok/hass-dreo#135] opened 2024-07-18 18:43 UTC
Include all of the following:
 - Model - MC710S
- Number of speeds the fan supports (not including "off")  12
- Does the fan support oscillating?  Yes 
- What preset modes are supported? Fan - normal, auto, sleep
- Is temperature supported? Yes

- Second motor drives the filter with the following settings - Auto, 1, 2, 3

Make sure you've installed this integration, then from the integration settings page, select **Download Diagnostics** and attach that file.
[config_entry-dreo-3248ff24b0436e1735925ede535fc5f4.json](https://github.com/user-attachments/files/16287696/config_entry-dreo-3248ff24b0436e1735925ede535fc5f4.json)

**Comment by JeffSteinbok** [comment] 2024-08-05 03:39
Duplicate of #134

**Closed by JeffSteinbok** 2024-08-05 03:39 UTC
Labels: new device request
