### ISSUE TITLE
Add Support for DR-HTF010S

### ISSUE THREAD

**Issue by mrpomander** [JeffSteinbok/hass-dreo#81] opened 2024-04-11 04:42 UTC
Model: DR-HTF010S
Number of Speeds: 12
Does the fan support oscillating: Yes
What preset modes are supported: Normal, Auto, Sleep
Is temperature supported: Yes

Thanks for all your work!

**Comment by JeffSteinbok** [comment] 2024-05-26 19:58
Dupe of #80

**Closed by JeffSteinbok** 2024-05-26 19:58 UTC
Labels: duplicate
