### ISSUE TITLE
Add support for DR-HAP002 Macro Pro Air Purifier

### ISSUE THREAD

**Issue by Monsterray** [JeffSteinbok/hass-dreo#76] opened 2024-03-17 19:40 UTC
Model: DR-HAP002
Number of speeds the fan supports (not including "off"): 20
Does the fan support oscillating?: NO
What preset modes are supported?: Auto, Turbo, Manual
Is temperature supported?: NO

The fan does track Air Quality though and I'm not sure how to get the info to help you get it integrated but am willing to help. There is also a Filter Health meter that shows how much life is left for the filter as a percentage. I did capture the Filter Life Reset command though below.

![IMG_6055](https://github.com/JeffSteinbok/hass-dreo/assets/1779600/f77b2103-3837-45c6-9ffe-6514fc2b9910)

`2024-03-17 12:23:15.603 DEBUG (DreoWebSocketStream) [pydreo] Message: {'method': 'control-report', 'devicesn': 'REDACTEDSN', 'messageid': 'b7828f70-1913-4152-a8aa-b2a99fa9db14', 'timestamp': 1710703395, 'reported': {'lifetime': 0}}
2024-03-17 12:23:22.846 DEBUG (DreoWebSocketStream) [pydreo] Message: {'method': 'control-report', 'devicesn': 'REDACTEDSN', 'messageid': 'f0ce0bcc-7fa8-4d66-9c62-9ff92dcdc63a', 'timestamp': 1710703402, 'reported': {'mode': 'turbo', 'windlevel': 20}}
2024-03-17 12:23:23.536 DEBUG (DreoWebSocketStream) [pydreo] Message: {'method': 'control-report', 'devicesn': 'REDACTEDSN', 'messageid': 'ad9f9aed-9139-411b-a913-ab1ff86b6269', 'timestamp': 1710703403, 'reported': {'mode': 'sleep', 'windlevel': 1, 'ledalwayson': False, 'muteon': True}}
2024-03-17 12:23:24.523 DEBUG (DreoWebSocketStream) [pydreo] Message: {'method': 'control-report', 'devicesn': 'REDACTEDSN', 'messageid': 'c2522123-4e35-45a1-a56d-083bbe7ebb67', 'timestamp': 1710703404, 'reported': {'mode': 'auto-regular', 'ledalwayson': True, 'muteon': False}}
2024-03-17 12:23:54.573 DEBUG (DreoWebSocketStream) [pydreo] Message: {'method': 'control-report', 'devicesn': 'REDACTEDSN', 'messageid': 'dbddcb46-2824-4dee-a69b-7b1fabdb8a91', 'timestamp': 1710703434, 'reported': {'mode': 'manual', 'windlevel': 4}}
2024-03-17 12:23:58.795 DEBUG (DreoWebSocketStream) [pydreo] Message: {'method': 'control-report', 'devicesn': 'REDACTEDSN', 'messageid': '2c8abaae-169c-4b8c-a32e-321bf1058efc', 'timestamp': 1710703438, 'reported': {'windlevel': 19}}
2024-03-17 12:24:07.219 DEBUG (DreoWebSocketStream) [pydreo] Message: {'method': 'control-report', 'devicesn': 'REDACTEDSN', 'messageid': '77990904-f16f-4ab0-9f4a-35576a44d6d6', 'timestamp': 1710703447, 'reported': {'ledalwayson': False}}
2024-03-17 12:24:08.480 DEBUG (DreoWebSocketStream) [pydreo] Message: {'method': 'control-report', 'devicesn': 'REDACTEDSN', 'messageid': 'd8affd9b-3dfe-4262-bb03-516f244fd9cb', 'timestamp': 1710703448, 'reported': {'ledalwayson': True}}
2024-03-17 12:24:09.468 DEBUG (DreoWebSocketStream) [pydreo] Message: {'method': 'control-report', 'devicesn': 'REDACTEDSN', 'messageid': '1dbf9f26-a305-451d-b493-d97df37ff70f', 'timestamp': 1710703449, 'reported': {'muteon': True}}
2024-03-17 12:24:39.669 DEBUG (DreoWebSocketStream) [pydreo] Message: {'method': 'control-report', 'devicesn': 'REDACTEDSN', 'messageid': '42afe03e-7403-47f3-81f8-1e0810fe24d5', 'timestamp': 1710703479, 'reported': {'muteon': False}}
2024-03-17 12:24:10.863 DEBUG (DreoWebSocketStream) [pydreo] Message: {'method': 'control-report', 'devicesn': 'REDACTEDSN', 'messageid': 'fd2606f1-4a93-48b2-b3e7-395b3986302e', 'timestamp': 1710703450, 'reported': {'childlockon': True}}
2024-03-17 12:24:11.592 DEBUG (DreoWebSocketStream) [pydreo] Message: {'method': 'control-report', 'devicesn': 'REDACTEDSN', 'messageid': 'cae468d4-2773-4a6b-956a-8751ee1f6bf5', 'timestamp': 1710703451, 'reported': {'childlockon': False}}
2024-03-17 12:24:19.267 DEBUG (DreoWebSocketStream) [pydreo] Message: {'method': 'control-report', 'devicesn': 'REDACTEDSN', 'messageid': '9a0483da-da5d-440f-a589-46f56c29a2c0', 'timestamp': 1710703459, 'reported': {'mode': 'manual'}}
2024-03-17 12:24:19.945 DEBUG (DreoWebSocketStream) [pydreo] Message: {'method': 'control-report', 'devicesn': 'REDACTEDSN', 'messageid': '92ab3d7e-548d-4f96-a9fb-eb36492dd848', 'timestamp': 1710703459, 'reported': {'mode': 'auto-regular', 'windlevel': 1}}
2024-03-17 12:24:53.962 DEBUG (DreoWebSocketStream) [pydreo] Message: {'method': 'control-report', 'devicesn': 'REDACTEDSN', 'messageid': '07420882-64f1-4838-ac14-95ba9c36ee9d', 'timestamp': 1710703493, 'reported': {'poweron': False}}
2024-03-17 12:24:54.690 DEBUG (DreoWebSocketStream) [pydreo] Message: {'method': 'control-report', 'devicesn': 'REDACTEDSN', 'messageid': 'f88fbfad-08b2-498e-8506-6952cd45eb13', 'timestamp': 1710703494, 'reported': {'poweron': True}}
2024-03-17 12:43:06.530 DEBUG (DreoWebSocketStream) [pydreo] Message: {'method': 'report', 'devicesn': 'REDACTEDSN', 'messageid': '79355eea-f16f-400c-aa98-fa600696a92e', 'timestamp': 1710704586, 'reported': {'muteon': True}}
2024-03-17 12:43:19.503 DEBUG (DreoWebSocketStream) [pydreo] Message: {'method': 'control-report', 'devicesn': 'REDACTEDSN', 'messageid': 'efd8b504-5a13-4e38-af8e-be85eb93789d', 'timestamp': 1710704599, 'reported': {'mode': 'auto-silent'}}
2024-03-17 12:43:22.573 DEBUG (DreoWebSocketStream) [pydreo] Message: {'method': 'control-report', 'devicesn': 'REDACTEDSN', 'messageid': 'bc67501f-f4e3-47cc-9ab6-613530bbb503', 'timestamp': 1710704602, 'reported': {'mode': 'auto-regular'}}`

**Comment by JeffSteinbok** [comment] 2024-04-07 22:17
Duplicate of #63

**Closed by JeffSteinbok** 2024-04-07 22:17 UTC
