### ISSUE TITLE
SyntaxWarning in 0.8.3

### ISSUE THREAD

**Issue by SeanPM5** [JeffSteinbok/hass-dreo#178] opened 2024-09-01 08:56 UTC
After installing 0.8.3 there's a warning in logs for my fan that I didn't see before (I have Pilot Max S Tower Fan / DR-HTF004S). Fan seems to work normally though.

```
This error originated from a custom integration.

Logger: py.warnings
Source: custom_components/dreo/pydreo/__init__.py:19
integration: Dreo (documentation, issues)
First occurred: 4:40:57 AM (1 occurrences)
Last logged: 4:40:57 AM

/config/custom_components/dreo/pydreo/pydreofan.py:142: SyntaxWarning: "is" with 'int' literal. Did you mean "=="? if (preset_modes.count is 0):
```

Also instead of 0.8.3 it says 0.1.3 on the device page, not sure if that's a mistake or not:

<img width="306" alt="Screen Shot 2024-09-01 at 4 52 04 AM" src="https://github.com/user-attachments/assets/a1bd3e8e-8fae-4a74-b412-a7f128bcb1c9">

**Comment by SeanPM5** [comment] 2024-09-01 08:58
Just noticed this also:

```
Logger: homeassistant.components.fan
Source: components/fan/__init__.py:295
integration: Fan ([documentation](https://www.home-assistant.io/integrations/fan), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+fan%22))
First occurred: 4:41:03 AM (2 occurrences)
Last logged: 4:41:06 AM

Entity None (<class 'custom_components.dreo.fan.DreoFanHA'>) does not set FanEntityFeature.TURN_OFF but implements the turn_off method. Please create a bug report at https://github.com/jeffsteinbok/hass-dreo/issues
Entity None (<class 'custom_components.dreo.fan.DreoFanHA'>) does not set FanEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/jeffsteinbok/hass-dreo/issues
```

**Comment by JeffSteinbok** [comment] 2024-09-01 09:10
Duplicate of #156

**Closed by JeffSteinbok** 2024-09-01 09:10 UTC
