### ISSUE TITLE
Warning in Log details (Home Assistant)

### ISSUE THREAD

**Issue by CrazyAngelFir3** [JeffSteinbok/hass-dreo#156] opened 2024-08-14 08:08 UTC
i do apologize, this is my first time posting anything here so I'm not entirely sure if it is correct as i following the detail report.
This has popped up after updating to 2024.8.0 (i think)
i updated it on the 14.8.24 

Logger: homeassistant.components.fan
Source: components/fan/__init__.py:295
integration: Fan (documentation, issues)
First occurred: 8:50:14 AM (8 occurrences)
Last logged: 8:50:14 AM

Entity None (<class 'custom_components.dreo.fan.DreoFanHA'>) does not set FanEntityFeature.TURN_OFF but implements the turn_off method. Please create a bug report at https://github.com/jeffsteinbok/hass-dreo/issues
Entity None (<class 'custom_components.dreo.fan.DreoFanHA'>) does not set FanEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/jeffsteinbok/hass-dreo/issues

**Comment by GentleHoneyLover** [comment] 2024-08-15 12:34
Same here. Noticed this after upgrading to HA 2024.8.1...

**Comment by JeffSteinbok** [comment] 2024-08-26 19:39
Duplicate of #154

**Closed by JeffSteinbok** 2024-08-26 19:39 UTC
