### ISSUE TITLE
DR-HCF001S no longer showing the fan entity since update

### ISSUE THREAD

**Issue by 67jeffh** [JeffSteinbok/hass-dreo#172] opened 2024-08-28 17:31 UTC
Using the previous version I could see the fan entity and the sound entity.  While the fan did not work as expected, it was present.  When I updated this week (Twice) the fan entity disappeared.

![Capture - Dreo](https://github.com/user-attachments/assets/670d8196-0dca-4d96-bef6-52568d49c71b)

Home Assistant

Core 2024.8.3
Supervisor 2024.08.0
Operating System 13.1
Frontend 20240809.0

**Comment by jasonnovak** [comment] 2024-08-28 20:47
I have the same issue

**Comment by 67jeffh** [comment] 2024-08-30 15:06
Adding the logs

[dreo ceiling fan.txt](https://github.com/user-attachments/files/16818891/dreo.ceiling.fan.txt)

**Comment by JeffSteinbok** [comment] 2024-09-01 03:52
I've put in a fix for the missing preset modes, but I can't figure out why you're not seeing the entity.
Can you try to sync from the latest commit in the attached branch and see if it works? 
If not, I need to look at more logging.

**Comment by JeffSteinbok** [comment] 2024-09-01 03:55
Also, for logging, do make sure you also enable logging for "dreo", not just "pydreo"

**Comment by jasonnovak** [comment] 2024-09-01 05:09
I'm seeing the same in #147 - here is my debug log in the new 0.8.3.

I used the panel sound option, the only one, and then controlled it manually from the IR remote

[home-assistant_2024-09-01T05-06-43.086Z.log](https://github.com/user-attachments/files/16827402/home-assistant_2024-09-01T05-06-43.086Z.log)

**Comment by JeffSteinbok** [comment] 2024-09-01 06:20
Given your recent logs, I think the code in **main** could work for you.  Do you know how to install a custom version to test?

**Comment by jasonnovak** [comment] 2024-09-01 12:41
I've installed 0.8.4 and the fan switch does appear again, but doesn't work properly, ie power button doesn't work, but slider does > added logs to #147

**Comment by JeffSteinbok** [comment] 2024-09-03 01:40
Going to call this a duplicate of #147

**Comment by JeffSteinbok** [comment] 2024-09-03 01:40
Duplicate of #147

**Closed by JeffSteinbok** 2024-09-03 01:40 UTC
Labels: bug
